### ISSUE TITLE
Using the playlist on local devices

### ISSUE THREAD

**Issue by dhanuhammer** [rabilrbl/jiotv_go#33] opened 2023-09-08 22:14 UTC
Is it possible for me to run this script locally on a device like raspberry pi, and use the playlist throughout my network?

**Comment by rabilrbl** [comment] 2023-09-09 03:09
As this is not a bug or feature request. I am closing this issue. For questions, either create a post in [discussion](https://github.com/rabilrbl/jiotv_go/discussions) or join our [Telegram Support Group](https://telegram.me/jiotv_go_chat)

Answer to your question:

Yes it is possible to run jiotv_go in a raspberry PI, I am assuming your PI uses arm arch processor. Hence choose linux-arm from releases.

Execute like below after providing permissions for the binary. Refer README.md
`./jiotv_go-..._linux-... ":5001"`
You can replace 5001 with any port of your choice. jiotv_go shall be accessible from local ip of rasPI.

Please remember that jiotv_go doesn't work outside India and VPN/VPS network.

**Closed by rabilrbl** 2023-09-09 03:09 UTC
