### ISSUE TITLE
Android: Execution issue

### ISSUE THREAD

**Issue by Mjsharma54** [rabilrbl/jiotv_go#11] opened 2023-08-31 10:56 UTC
chmod + jiotv_go-v0.5.3-darwin-amd64
~ $ ./jiotv_go-v0.5.3-darwin-amd64
bash: ./jiotv_go-v0.5.3-darwin-amd64: cannot execute binary file: Exec format error
~ $

**Comment by siddharthsky** [comment] 2023-08-31 15:08
> chmod + jiotv_go-v0.5.3-darwin-amd64 ~ $ ./jiotv_go-v0.5.3-darwin-amd64 bash: ./jiotv_go-v0.5.3-darwin-amd64: cannot execute binary file: Exec format error ~ $

you missed "x".

chmod **+x** jiotv_go-v0.5.3-darwin-amd64

**Comment by rabilrbl** [comment] 2023-08-31 16:03
@Mjsharma54 If the problem is solved, please close this issue.

**Comment by Mjsharma54** [comment] 2023-08-31 16:46
chmod +x jiotv_go-v0.5.3-darwin-amd64
~ $ ./jiotv_go-v0.5.3-darwin-amd64
bash: ./jiotv_go-v0.5.3-darwin-amd64: cannot execute binary file: Exec format error
~ $

**Comment by Mjsharma54** [comment] 2023-08-31 16:46
Problem still same

**Comment by Mjsharma54** [comment] 2023-08-31 17:27
GIN] 2023/08/31 - 17:26:36 | 500 |   22.633334ms |       127.0.0.1 | GET      "/"

**Comment by siddharthsky** [comment] 2023-08-31 18:04
> GIN] 2023/08/31 - 17:26:36 | 500 | 22.633334ms | 127.0.0.1 | GET "/"

Try this binary:
[ jiotv_go-v0.5.3-android-arm64-local](https://github.com/siddharthsky/Extrix/raw/main/builds/android-jiotv-go-local/jiotv_go-v0.5.3-android-arm64-local)

Steps:

1. `wget https://github.com/siddharthsky/Extrix/raw/main/builds/android-jiotv-go-local/jiotv_go-v0.5.3-android-arm64-local`

2. `chmod +x jiotv_go-v0.5.3-android-arm64-local`

3. `.\jiotv_go-v0.5.3-android-arm64-local`

**Comment by rabilrbl** [comment] 2023-09-01 01:08
@Mjsharma54 use these 👆

**Comment by siddharthsky** [comment] 2023-09-01 04:41
> @siddharthsky what were those builds?
> 
> You are free to have your own version of jiotv_go, only with open source code and same licence. Don't post otherwise.
> 
> If you are testing something, please also mention the same.
> 
> > The reason why I stopped android builds is because, linux builds are running fine in termux. Android builds had more error compared to linux builds

@rabilrbl There is nothing new in the build I [provided](https://github.com/siddharthsky/Extrix/raw/main/builds/android-jiotv-go-local/jiotv_go-v0.5.3-android-arm64-local) . I manually built in on Android arm64 by cloning the [main repo](https://github.com/rabilrbl/jiotv_go).

Because the Linux builds from current build and Android builds from previous builds were not working at all for me. [ connection refused error ]. Still trying to figure out what was there problem with automatic builds.

> GIN] 2023/08/31 - 17:26:36 | 500 | 22.633334ms | 127.0.0.1 | GET "/"


The manually built version is working without a hiccup on Android. You can try.

**Comment by rabilrbl** [comment] 2023-09-01 05:39
@siddharthsky I have figured out the error, the error is related to golang, where it fails to lookup for DNS. As mentioned in  https://github.com/golang/go/issues/8877 . I will be testing thoroughly and pushing a fix with custom DNS settings.

**Comment by Mjsharma54** [comment] 2023-09-01 07:22
@siddharthsky thanks bro now working for me

**Comment by rabilrbl** [comment] 2023-09-01 17:36
@siddharthsky I have applied fix for dns resolution error on Android, please test the latest build v0.5.4 and see if error persist

**Comment by siddharthsky** [comment] 2023-09-01 18:36
> [@siddharthsky](https://github.com/siddharthsky) I have applied fix for dns resolution error on Android, please test the latest build v0.5.4 (linux build) and see if error persist

Tested : jiotv\_go-v0.5.4-linux-arm64 on Termux

Tried :  

*     `./jiotv_go-v0.5.4-linux-arm64` \[working\] 🎉
    *   index page   ✅
    *   channel playing   ✅
    *   IPTV via playlist   ✅
*    `./jiotv_go-v0.5.4-linux-arm64 :7777` \[working\] 🎉 
    *   index page   ✅
    *   channel playing   ✅
    *   IPTV via playlist   ✅
*    `./jiotv_go-v0.5.4-linux-arm64 192.168.1.111:3500` \[partially working\]
    *   index page   ✅
    *   channel playing   ❌
    *   IPTV via playlist   ✅

<p align="center">
    <img src="https://i.imgur.com/0TOEJc2m.png" alt="SC" />
</p>

**Comment by rabilrbl** [comment] 2023-09-02 05:45
@siddharthsky why do you want to specify an ip?

**Comment by siddharthsky** [comment] 2023-09-02 05:52
> @siddharthsky why do you want to specify an ip?

As mentioned in https://github.com/rabilrbl/jiotv_go/issues/5#issuecomment-1694731294

For using phone as a server for hosting and using IPTV m3u on TV.

**Comment by rabilrbl** [comment] 2023-09-02 05:54
@siddharthsky for that `./jiotv_go :5001`
Now you can access jiotv_go from all your local network using devices local ip

**Comment by siddharthsky** [comment] 2023-09-02 07:04
> [@siddharthsky](https://github.com/siddharthsky) for that `./jiotv_go :5001`  
> Now you can access jiotv\_go from all your local network using devices local ip

@rabilrbl Yes, 

But same site accessed through

*    `localhost:5001` \[working\] 🎉 
    *   index page   ✅
    *   channel playing   ✅
    *   IPTV via playlist   ✅
*   via device IP  `192.168.1.111:5001` \[partially working\]
    *   index page   ✅
    *   channel playing   ❌
    *   IPTV via playlist   ✅
    

Tested on same device.

**Comment by rabilrbl** [comment] 2023-09-02 07:17
Send me logs both frontend and back-end

**Comment by siddharthsky** [comment] 2023-09-02 07:52
[frontend-console-export-2023-9-2_13-9-9.txt](https://github.com/rabilrbl/jiotv_go/files/12503430/frontend-console-export-2023-9-2_13-9-9.txt)
[log.txt](https://github.com/rabilrbl/jiotv_go/files/12503445/log.txt)

**Comment by rabilrbl** [comment] 2023-09-02 09:09
@siddharthsky this is CORS request origin error, solely front end problem

**Comment by rabilrbl** [comment] 2023-09-02 09:34
@siddharthsky nice catch 😁, I couldn't find otherwise, the error is related to flowplayer, I'll need to change the player once again. Will push v0.6.0 with new player

**Closed** 2023-09-02 09:41 UTC

**Comment by rabilrbl** [comment] 2023-09-02 09:43
@siddharthsky I have pushed a hot fix v0.5.6 should be playable. Check and lemme know

**Comment by siddharthsky** [comment] 2023-09-02 10:58
> @siddharthsky I have pushed a hot fix v0.5.6 should be playable. Check and lemme know

It has fixed the issue.
