### ISSUE TITLE
feat: Zee cinema, flix etc movie channels are missing recently 

### ISSUE THREAD

**Issue by amtabhshk** [rabilrbl/jiotv_go#433] opened 2024-09-17 13:53 UTC
### Feature description

Movie channels missing recently 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by itsyourap** [comment] 2024-09-18 10:29
Duplicate of #425

**Closed** 2024-09-18 14:55 UTC
Labels: duplicate
