### ISSUE TITLE
Bug: `fatal error: concurrent map iteration and map write` in net/http

### ISSUE THREAD

**Issue by krz123** [rabilrbl/jiotv_go#31] opened 2023-09-07 08:33 UTC
I am using this command in my phone

JIOTV_CREDENTIALS_PATH=credentials.json
JIOTV_DNS=1.1.1.1
./jiotv_go-v0.5.8-linux-arm64 "192.168.4.101:8080"

After run command starts working and also i am using in TV Remotely.but after some time stops working automatically. I have to run the command again ./jiotv_go-v0.5.8-linux-arm64 "192.168.4.101:8080"

Thank you.

**Comment by rabilrbl** [comment] 2023-09-07 09:06
Don't provide JIOTV_CREDENTIALS_PATH and JIOTV_DNS as your using default values.

Run it like `./jiotv_go-v0.5.8-linux-arm64 ":8080"`

After executing like this, if you are facing problem, send logs from terminal with appropriate screenshots

**Comment by krz123** [comment] 2023-09-07 14:51
![Screenshot_20230907-201934](https://github.com/rabilrbl/jiotv_go/assets/27541533/5a2e9e73-2b06-42c9-8205-cba3f8373dd7)

**Comment by rabilrbl** [comment] 2023-09-07 14:55
> ![Screenshot_20230907-201934](https://user-images.githubusercontent.com/27541533/266356166-5a2e9e73-2b06-42c9-8205-cba3f8373dd7.png)

Scroll  up and send full ss

**Comment by rabilrbl** [comment] 2023-09-07 15:51
As per @krz123 Sent SS on telegram, the issue is related to `fatal concurrent map iteration and map write` as in screenshot below

| SS1 | SS2 |
| - | - |
| ![photo_2023-09-07_20-52-31](https://github.com/rabilrbl/jiotv_go/assets/63334479/03dbb228-f30f-4898-aaee-b09d5b92592b) | ![photo_2023-09-07_20-52-31 (2)](https://github.com/rabilrbl/jiotv_go/assets/63334479/978cc568-8feb-4269-afe5-61b4509932bd) |

**Comment by rabilrbl** [comment] 2023-09-09 03:16
As it turns out, I frankly have no idea, what's causing concurrent map iteration. Mostly It is related to updating and deleting header in net/http request in `/render.m3u8` route. I can push a fix using `mutex`. But for the  moment I am planning to change to fasthttp as we have gofiber migration upcoming.

**Comment by dheerajv4855** [comment] 2023-09-09 14:13
> 
gin, gofiber is just routing framework so we cannot say this issue wont come with gofiber migration
for now 
i have code fix related to mutex and that is working fine

**Comment by rabilrbl** [comment] 2023-09-09 16:02
@dheerajv4855 As mentioned in your PR.

gofiber is built on top of fasthttp, similar to gin built on top net/http, hence fasthttp is an alternative to net/http, So i migrated from net/http to fasthttp. fasthttp performs well on concurrency. But net/http is better with standards, which is not relevant in our small application.

**Comment by rabilrbl** [comment] 2023-09-09 16:25
Fixed in #30

**Closed by rabilrbl** 2023-09-09 16:25 UTC
